CREATE USER postgres WITH PASSWORD 'JkP%7NqgGGj8TGJz' SUPERUSER;
CREATE DATABASE postgres WITH OWNER postgres;

CREATE ROLE "postgres" LOGIN PASSWORD 'JkP%7NqgGGj8TGJz';
GRANT CREATE ON DATABASE postgres TO "postgres";